

"""
Revision ID: e25f01736900
Revises: 0001_initial
Create Date: 2026-01-24 04:02:02.767171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25f01736900'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    try:
        op.create_table('wishlist_item',
            sa.Column('wishlist_item_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('wishlist_id', sa.BigInteger(), nullable=False),
            sa.Column('product_id', sa.BigInteger(), nullable=False),
            sa.Column('variant_id', sa.BigInteger(), nullable=True),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.BigInteger(), nullable=True),
            sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.wishlist_id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
            sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
            sa.PrimaryKeyConstraint('wishlist_item_id')
        )
    except Exception as e:
        print(f"Warning: could not create 'wishlist_item' table (likely already exists): {e}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('street_line_1', sa.String(length=255), nullable=True),
    sa.Column('street_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_snapshot_id'), 'address_snapshot', ['id'], unique=False)
    try:
        op.create_table('category',
            sa.Column('category_id', sa.BigInteger(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('image_url', sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint('category_id')
        )
    except Exception as e:
        print(f"Warning: could not create 'category' table (likely already exists): {e}")
    op.create_table('customer_component',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('employee_snapshot',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('full_name')
    )
    op.create_table('payment_snapshot',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_full_name', sa.String(length=255), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('last4_digits', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paystub_snapshot',
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('incident_number', sa.BigInteger(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('sick_days', sa.Integer(), nullable=True),
    sa.Column('pto_days', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('gross_pay', sa.Float(), nullable=True),
    sa.Column('deductions', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_name')
    )
    op.create_table('pto_snapshot',
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('incident_number', sa.BigInteger(), nullable=True),
    sa.Column('pto_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_name')
    )
    op.create_table('refund_snapshot',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('payment_user_name', sa.String(length=255), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reimbursement_snapshot',
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('incident_number', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_name')
    )
    op.create_table('seller_component',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_snapshot',
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('seller_type', sa.String(length=50), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('store_name')
    )
    op.create_table('sickday_snapshot',
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('incident_number', sa.BigInteger(), nullable=True),
    sa.Column('sick_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_name')
    )
    op.create_table('user_snapshot',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('full_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('img_location', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    try:
        op.create_table('cart',
            sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('user_id', sa.BigInteger(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
            sa.PrimaryKeyConstraint('cart_id')
        )
    except Exception as e:
        print(f"Warning: could not create 'cart' table (likely already exists): {e}")
    op.create_table('customer_shipment',
    sa.Column('cs_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('street_line_1', sa.String(length=255), nullable=True),
    sa.Column('street_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cs_id')
    )
    op.create_table('employee',
    sa.Column('emp_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_table('employee_component',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('manager_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_table('seller_payout',
    sa.Column('payout_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('date_of_payment', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'completed', name='payoutstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payout_id')
    )
    op.create_table('subcategory',
    sa.Column('subcategory_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('subcategory_id')
    )
    op.create_table('user_finance',
    sa.Column('uf_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('pin', sa.String(length=4), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('credit_card_number', sa.String(length=16), nullable=True),
    sa.Column('account_type', sa.Enum('cheque', 'credit', name='accounttypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('uf_id')
    )
    op.create_table('wishlist',
    sa.Column('wishlist_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wishlist_id')
    )
    op.create_table('employee_pto',
    sa.Column('pto_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='ptostatusenum'), nullable=True),
    sa.Column('approved_by_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_manager_id'], ['manager.manager_id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.emp_id'], ),
    sa.PrimaryKeyConstraint('pto_id')
    )
    op.create_table('employee_sickday',
    sa.Column('sickday_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='ptostatusenum'), nullable=True),
    sa.Column('approved_by_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_manager_id'], ['manager.manager_id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.emp_id'], ),
    sa.PrimaryKeyConstraint('sickday_id')
    )
    op.create_table('finance_employee',
    sa.Column('finance_emp_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.emp_id'], ),
    sa.PrimaryKeyConstraint('finance_emp_id')
    )
    op.create_table('incident',
    sa.Column('incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('status_addressed', sa.Boolean(), nullable=True),
    sa.Column('paid_all', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.emp_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('cart_id', sa.BigInteger(), nullable=True),
    sa.Column('order_status', sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned', name='orderstatusenum'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_number', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('subcategory_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.subcategory_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('shift',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_emp_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_by_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'canceled', name='shiftstatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_emp_id'], ['employee.emp_id'], ),
    sa.ForeignKeyConstraint(['created_by_manager_id'], ['manager.manager_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('employee_payment',
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('emp_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'completed', name='payoutstatusenum'), nullable=True),
    sa.Column('processed_by_finance_emp_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.emp_id'], ),
    sa.ForeignKeyConstraint(['processed_by_finance_emp_id'], ['finance_employee.finance_emp_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('product_comment',
    sa.Column('comment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('product_image',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('product_rating',
    sa.Column('rating_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_table('product_variant',
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_table('refund_request',
    sa.Column('refund_request_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_item_ids', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('date_of_request', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('refund_request_id')
    )
    op.create_table('reimbursement',
    sa.Column('reimbursement_id', sa.BigInteger(), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.Column('amount_approved', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('status_addressed', sa.Boolean(), nullable=True),
    sa.Column('paid_all', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.incident_id'], ),
    sa.PrimaryKeyConstraint('reimbursement_id')
    )
    op.create_table('sellers_expense',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_request',
    sa.Column('shift_request_id', sa.BigInteger(), nullable=False),
    sa.Column('shift_id', sa.BigInteger(), nullable=True),
    sa.Column('requesting_emp_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_by_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='ptostatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_manager_id'], ['manager.manager_id'], ),
    sa.ForeignKeyConstraint(['requesting_emp_id'], ['employee.emp_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.shift_id'], ),
    sa.PrimaryKeyConstraint('shift_request_id')
    )
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('shipment_status', sa.Enum('created', 'pending', 'packed', 'shipped', 'in_transit', 'delivered', 'failed', 'returned', name='shipmentstatusenum'), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_index(op.f('ix_shipment_shipment_id'), 'shipment', ['shipment_id'], unique=False)
    op.create_table('cart_item',
    sa.Column('cart_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_item_order_item_id'), 'order_item', ['order_item_id'], unique=False)
    op.create_table('product_review',
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('rating_id', sa.BigInteger(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['product_rating.rating_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('product_variant_image',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('return_shipment',
    sa.Column('return_shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('original_shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('return_status', sa.String(length=50), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('return_shipment_id')
    )
    op.create_table('shipment_address',
    sa.Column('shipment_address_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('shipment_address_id')
    )
    op.create_table('shipment_event',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('shipment_issue',
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('shipment_employee_name', sa.String(length=255), nullable=True),
    sa.Column('issue_type', sa.Enum('damaged', 'lost', 'delayed', 'undeliverable', name='issuetypeenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('appointted_to', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('shipping_snapshot',
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('refund',
    sa.Column('refund_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_cs_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'processed', name='refundstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_cs_id'], ['employee.emp_id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.order_item_id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_table('seller_review_response',
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=True),
    sa.Column('seller_id', sa.BigInteger(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['product_review.review_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('shipment_item',
    sa.Column('shipment_item_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('shipment_event_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['shipment_event_id'], ['shipment_event.event_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ),
    sa.PrimaryKeyConstraint('shipment_item_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_item')
    op.drop_table('seller_review_response')
    op.drop_table('refund')
    op.drop_table('shipping_snapshot')
    op.drop_table('shipment_issue')
    op.drop_table('shipment_event')
    op.drop_table('shipment_address')
    op.drop_table('return_shipment')
    op.drop_table('product_variant_image')
    op.drop_table('product_review')
    op.drop_index(op.f('ix_order_item_order_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_shipment_shipment_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_table('shift_request')
    op.drop_table('sellers_expense')
    op.drop_table('reimbursement')
    op.drop_table('refund_request')
    op.drop_table('product_variant')
    op.drop_table('product_rating')
    op.drop_table('product_image')
    op.drop_table('product_comment')
    op.drop_table('payment')
    op.drop_table('employee_payment')
    op.drop_table('shift')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('incident')
    op.drop_table('finance_employee')
    op.drop_table('employee_sickday')
    op.drop_table('employee_pto')
    op.drop_table('wishlist')
    op.drop_table('user_finance')
    op.drop_table('subcategory')
    op.drop_table('seller_payout')
    op.drop_table('manager')
    op.drop_table('employee_component')
    op.drop_table('employee')
    op.drop_table('customer_shipment')
    op.drop_table('cart')
    op.drop_table('users')
    op.drop_table('user_snapshot')
    op.drop_table('sickday_snapshot')
    op.drop_table('seller_snapshot')
    op.drop_table('seller_component')
    op.drop_table('reimbursement_snapshot')
    op.drop_table('refund_snapshot')
    op.drop_table('pto_snapshot')
    op.drop_table('paystub_snapshot')
    op.drop_table('payment_snapshot')
    op.drop_table('employee_snapshot')
    op.drop_table('department')
    op.drop_table('customer_component')
    op.drop_table('category')
    op.drop_index(op.f('ix_address_snapshot_id'), table_name='address_snapshot')
    op.drop_table('address_snapshot')
    # ### end Alembic commands ###
