from abc import ABC, abstractmethod

class IFinanceService(ABC):
    @abstractmethod
    async def get_issues_catalog(self): ...
    @abstractmethod
    async def get_issue_detail(self, issue_id): ...
    @abstractmethod
    async def create_issue(self, employee_id, description, cost, date, status): ...
    @abstractmethod
    async def update_issue(self, issue_id, **kwargs): ...
    @abstractmethod
    async def delete_issue(self, issue_id, confirm=False): ...
    @abstractmethod
    async def get_reimbursements_catalog(self): ...
    @abstractmethod
    async def get_reimbursement_detail(self, reimbursement_id): ...
    @abstractmethod
    async def update_reimbursement(self, reimbursement_id, **kwargs): ...
    @abstractmethod
    async def delete_reimbursement(self, reimbursement_id, confirm=False): ...
    @abstractmethod
    async def add_reimbursement_report(self, incident_id, description, amount_approved=None, response=None): ...
    @abstractmethod
    async def get_reimbursement(self, reimbursement_id): ...
    @abstractmethod
    async def get_all_reimbursements(self): ...
    @abstractmethod
    async def calculate_total_payment(self, employee_id, start_date, end_date): ...
